//! Report Module
//! 
//! Logs iterations and generates final reports.

use crate::metrics::IterationRecord;
use std::fs::{File, OpenOptions};
use std::io::{BufWriter, Write};
use std::path::Path;

/// Report generator
pub struct ReportGenerator {
    output_dir: std::path::PathBuf,
    jsonl_file: Option<BufWriter<File>>,
    iteration_count: u32,
}

impl ReportGenerator {
    /// Create a new report generator
    pub fn new(output_dir: &Path) -> anyhow::Result<Self> {
        std::fs::create_dir_all(output_dir)?;
        
        let jsonl_path = output_dir.join("autoresearch.jsonl");
        let file = OpenOptions::new()
            .create(true)
            .append(true)
            .open(&jsonl_path)?;
        
        Ok(Self {
            output_dir: output_dir.to_path_buf(),
            jsonl_file: Some(BufWriter::new(file)),
            iteration_count: 0,
        })
    }
    
    /// Log an iteration
    pub fn log_iteration(&mut self, record: &IterationRecord) -> anyhow::Result<()> {
        self.iteration_count += 1;
        
        if let Some(ref mut writer) = self.jsonl_file {
            let json = serde_json::to_string(record)?;
            writeln!(writer, "{}", json)?;
            writer.flush()?;
        }
        
        // Print progress
        println!(
            "Iteration {}: F1={:.3}, FP={:.1}%, Detection={:.1}%, Obj={:.3} [{}]",
            record.iteration,
            record.f1_score,
            record.fp_rate * 100.0,
            record.detection_rate * 100.0,
            record.objective_score,
            if record.accepted { "✓" } else { "✗" }
        );
        
        Ok(())
    }
    
    /// Generate final report
    pub fn generate_final_report(&self, best_record: &IterationRecord) -> anyhow::Result<()> {
        let report_path = self.output_dir.join("final-report.md");
        let mut file = File::create(&report_path)?;
        
        let report = format!(
            r#"# Autoresearch Final Report

**Generated:** {}
**Total Iterations:** {}

## Best Configuration Found

| Metric | Value |
|--------|-------|
| **F1 Score** | {:.3} |
| **FP Rate** | {:.1}% |
| **Detection Rate** | {:.1}% |
| **Objective Score** | {:.3} |

## Parameters

| Parameter | Value |
|-----------|-------|
| malicious_threshold | {} |
| suspicious_threshold | {} |
| reputation_tier_1 | {} |
| reputation_tier_2 | {} |
| llm_override_threshold | {} |
| llm_multiplier_min | {} |
| category_cap_1 | {} |
| category_cap_2 | {} |
| category_cap_3 | {} |
| dedup_similarity | {} |
| log_weight_base | {} |

## Convergence

- Best iteration: {}
- Total iterations run: {}

## Next Steps

1. Apply the best configuration to `glassware/src/scoring_config.rs`
2. Run full validation on Phase A packages
3. Verify FP rate ≤5% and evidence detection ≥90%
4. Proceed to Phase B if validation passes

---

*Generated by glassware-tools autoresearch*
"#,
            chrono::Utc::now().to_rfc3339(),
            self.iteration_count,
            best_record.f1_score,
            best_record.fp_rate * 100.0,
            best_record.detection_rate * 100.0,
            best_record.objective_score,
            best_record.parameters["malicious_threshold"],
            best_record.parameters["suspicious_threshold"],
            best_record.parameters["reputation_tier_1"],
            best_record.parameters["reputation_tier_2"],
            best_record.parameters["llm_override_threshold"],
            best_record.parameters["llm_multiplier_min"],
            best_record.parameters["category_cap_1"],
            best_record.parameters["category_cap_2"],
            best_record.parameters["category_cap_3"],
            best_record.parameters["dedup_similarity"],
            best_record.parameters["log_weight_base"],
            best_record.iteration,
            self.iteration_count,
        );
        
        writeln!(file, "{}", report)?;
        
        println!("\nFinal report written to: {:?}", report_path);
        
        Ok(())
    }
    
    /// Get iteration count
    pub fn iteration_count(&self) -> u32 {
        self.iteration_count
    }
}

impl Drop for ReportGenerator {
    fn drop(&mut self) {
        if let Some(ref mut writer) = self.jsonl_file {
            let _ = writer.flush();
        }
    }
}
